ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:
:toc-placement!:

= `collectionspace-mapper` batch configuration options

toc::[]

A JSON config hash may be passed to a new `Mapper::DataHandler` to control various aspects of the data transformation. 

.Example config JSON
[source,javascript]
----
{
  "delimiter": ";",
  "subgroup_delimiter": "^^",
  "response_mode": "verbose",
  "check_terms" : true,
  "check_record_status" : true,
  "force_defaults": false,
  "transforms": {
    "collection": {
      "special": [
        "downcase_value"
      ],
      "replacements": [{
        "find": " ",
        "replace": "-",
        "type": "plain"
      }]
    }
  },
  "default_values": {
    "publishTo": "DPLA;Omeka",
    "collection": "library-collection"
  },
  "ambiguous_month_day": "as_month_day",
  "ambiguous_month_year": "as_year"
}
----

[NOTE]
====
See https://github.com/kspurgin/emendate/blob/main/docs/options.adoc for details on date-related configuration options.
====

== `delimiter`

Delimiter character or string used to split repeatable values within the cell of a CSV. 

- *Required?:* yes
- *Defaults to:* |
- *Data type*: string

== `subgroup_delimiter`

Delimiter character or string used to split repeatable values nested inside other repeatable values (example: titleTranslation, titleTranslationLanguage).

This is only used when if you are importing data into a repeatable field group within a larger repeatable field group.

- *Required?:* yes
- *Defaults to:* ^^
- *Data type*: string

== `response_mode`

If `normal`, `Mapper::Response.orig_data` returns the original data hash, and `Mapper::Response.doc` returns the resulting XML document.

If `verbose`, `Mapper::Response` also has the following attributes, which may be helpful in debugging:

- `.merged_data` - result of merging any default values into `orig_data`.
- `.split_data` - result of splitting `merged_data` using `delimiter` and `subgroup_delimiter`. All field values are now arrays.
- `.transformed_data` - result of any transformations applied to `split_data`.
- `.combined_data` - result of combining separate data columns (such as `approvedByPerson` and `approvedByOrganization`) into one CollectionSpace field (`approvedBy`).  

- *Required?:* yes
- *Defaults to:* normal
- *Data type*: string
- *Allowed values*: `normal`, `verbose`

== `check_terms`

If `true`, looks up each term via `collectionspace-refcache`. If found, uses existing refname. If not found, searches for term via cspace-services API and uses existing refname if found. If term not found in refcache or services API, builds a new refname, uses that in the record, adds it to refcache, and returns the term with `found=false` in `Response::Terms`.

If `false`, never searches services API for the term. Uses refcache refname if it exists, otherwise builds a new refname and adds it to refcache. Returns all terms with `found=false` in `Response::Terms`.

[NOTE]
====
Set this to false only if you are certain no terms from your data exist in CollectionSpace, and all of the terms need to be created as new. Otherwise, you may end up with duplicate terms being added to CollectionSpace, due to the fact that `collectionspace-mapper` does not generate exactly the same hashed short identifier value for use in the refname as the CollectionSpace application does.
====

- *Required?:* yes
- *Defaults to:* true
- *Data type*: boolean
- *Allowed values*: `true`, `false`

== `check_record_status`

If `true`, looks up each record via cspace-services API and sets `Response.record_status` to `:exists` if the record is found, or `:new` if it is not. 

If `false`, does not search services API for the record. Sets `Response.record_status` to `:new`.

[NOTE]
====
Set this to false only if you are certain no records in your data exist in CollectionSpace. Otherwise, `cspace-batch-import` record transfer processes will fail for records that already exist.
====

- *Required?:* yes
- *Defaults to:* true
- *Data type*: boolean
- *Allowed values*: `true`, `false`

== `force_defaults`

Only has an effect if you are also providing `default_values` in your config.

Relevant if some fields for which you are providing `default_values` have other values in the source data (CSV). 

If `false`, default values will not replace or be added to values passed in via the data hash; default value will be inserted if field is missing or empty in data hash.

If `true`, default value will replace any data hash values.

- *Required?:* yes
- *Defaults to:* false
- *Data type*: boolean
- *Allowed values*: `true`, `false`


== `:transforms`

optional - Hash - Key (String) is the data hash field to which the transforms should be applied. Value (Hash) is structured transformation instructions.

== `:default_values`

optional - Hash - Key (String) is the data hash field that should be populated. Value (String) is the default value for the field.


