= Testing instructions for DDD

== Background
https://www.collectionspace.org/[CollectionSpace] is a collections management application for museums.

We are currently in the middle of an upgrade from CollectionSpace 6.0 to 6.1. *Our work here will focus on version 6.1.*

=== Profiles

Since there are very different types of museum collections (art museum vs. local history museum vs. botanical garden), CollectionSpace offers several different data profiles, all based on the core CollectionSpace profile.

|====================
| Profile | Demo site | Dev site

| Core | https://core.collectionspace.org | https://core.dev.collectionspace.org
| Anthropology  | https://anthro.collectionspace.org | https://anthro.dev.collectionspace.org
| Bonsai  | https://bonsai.collectionspace.org | https://bonsai.dev.collectionspace.org
| Botanical garden  | https://botgarden.collectionspace.org | https://botgarden.dev.collectionspace.org
| Fine & contemporary art  | https://fcart.collectionspace.org | https://fcart.dev.collectionspace.org
| Herbarium  | https://herbarium.collectionspace.org | https://herbarium.dev.collectionspace.org
| Local history & material culture  | https://lhmc.collectionspace.org | https://lhmc.dev.collectionspace.org
| Materials  | https://materials.collectionspace.org | https://materials.dev.collectionspace.org
| Public art  | https://publicart.collectionspace.org | https://publicart.dev.collectionspace.org
|====================

[NOTE]
====
The user name and password for the demo and dev sites are given on the login page. The username follows a consistent pattern across the profiles, and the password for all is the same. The login for demo and dev sites for each profile is the same.
====


[NOTE]
====
The bottom right corner of the login screen tells you the release of CollectionSpace used.

As of 2020-08-31, the demo sites are running 6.0 and the dev sites are running 6.1. *Since we are focusing on 6.1, start off using the dev sites.*

_*If the upgrade is completed during the time you are working on this project, you may see the dev sites jump to 6.2, in which case, you should start using the demo sites which will then be running 6.1.*_
====

=== Record types

There are three main types of record in CollectionSpace: collectionobject, procedure, and authority. To view any record type, open CollectionSpace, click `Create New`, and choose the record type.

collectionobject:: Also called "object" or "cataloging," this record describes an object in a museum's collection. This is the most complex record, with the most fields.
procedure:: A record of this type describes some action taken on an object or group of objects, such as acquisition, conservation activities, exhibition, or movement from one location to another. A procedure record is almost always linked to one or more object records. Procedure records may also be linked to each other. For example, if an object is moved for an exhibition, the movement record and exhibition record may be linked. 
authority:: A record of this type describes a term in a controlled vocabulary (concept, person, geographic place, storage location, etc.). Terms represented by an authority record may be used as values in fields in other records. Some fields require use of an authority term.

There are also vocabulary records, which we tend to deal with only indirectly. A vocabulary is sort of a lightweight version of an authority. It is a controlled term list, but not as much information can be recorded about a term. Some fields require use of a vocabulary term. To view vocabularies and terms in them, log into CollectionSpace, click `Tools`, and click `Term Lists` if you are not already on that tab.

Users with certain permission levels can add new authority and vocabulary terms in the CollectionSpace user interface.

There is another type of controlled term list that must be configured in the CollectionSpace application configuration. This is the "option list." Some fields require option list terms. 

An overview of the different profiles and record types is available on the https://collectionspace.atlassian.net/wiki/spaces/COL/pages/506953729/Configuration+and+Data+Maps+-+Cataloging+Procedures+and+Vocabularies[CollectionSpace wiki]. A comprehensive, sortable, filterable list of all fields in all record types in all profiles is available https://github.com/collectionspace/cspace-config-untangler/blob/master/data/fields_6_1_dates_collapsed.csv[here].


== This project

We are building a new batch data import tool that will allow CollectionSpace users to ingest new records or update existing records in bulk, by uploading a CSV file. The working documentation and discussion of the functional design for this tool https://collectionspace.atlassian.net/wiki/spaces/COL/pages/1267236875/CSV+Import+Tool[is available] if you are interested, but *you do not need to look at it*.

This repo represents _one piece_ of this batch data import tool. See https://github.com/collectionspace/collectionspace-mapper/blob/master/README.md[the main repo README file] for a description of what this piece does and how it fits in with the rest.

*The objective of your work on this project is to increase automated test coverage for the code in this repo.* This will include:

- creation of sample CollectionSpace record and saving XML representation of that record via the API
- creation of sample data that would result in that CollectionSpace record
- set up of tests using the sample data and CollectionSpace XML

More details on these steps below!

There are some known issues in the current code, and new tests that fail will help us uncover others, as well as to maintain the functionality of the code as changes are made going forward.


== Getting started

- https://github.com/collectionspace/collectionspace-mapper/blob/master/doc/setup_for_development.adoc[Get set up for development]

== Organizing the work (+ useful reference info)

https://docs.google.com/spreadsheets/d/1nhJRbgGjl7ZCTNlFFI1PnrpoJe-fDML5zMrS275HS3Q/edit?usp=sharing[Google Sheets file for organizing the work]

I gave Erick, Kevin, and Kamore permission to edit the file, so the link should work for you if you log in with a Google account linked to your DDD email.

CollectionSpace isn't always totally consistent, so this spreadsheet also serves as a reference for the internal/code names of different record types, how those record types are _usually_ displayed in the UI, and the pattern for using the CollectionSpace API to retrieve an XML version of a record created in the application.

Priority 1 is highest priority. I will add numbers as the work proceeds.

Put your name in the `claimed_by` column before starting work on a record type, so work doesn't get duplicated.

== Steps

The following steps assume I've chosen the objectexit record type from the bonsai profile.

=== 1. Prepare

. Choose a record type from the spreadsheet to work on and put your name in the `claimed_by` column.
. `cd` into this repo's folder
. `git checkout master` (if not already on master)
. `git pull`
. Create a new branch off master and switch to it: `git checkout -b bonsai-objectexit`
. Log into bonsai CollectionSpace > `Create New` > `Object Exit`

=== 2. Fully populate record in CollectionSpace and save XML

. Fill in the record as fully as possible -- my sample record is at `https://bonsai.dev.collectionspace.org/cspace/bonsai/record/objectexit/5f12d2f9-de20-4c77-9a93`.
.. For repeatable fields or groups of fields, enter more than one value
.. For repeatable field groups, make sure all fields are populated in at least one of the repetitions, but leave a field or two blank, especially in the first grouping, to ensure the mapper can handle these properly. (see the `Deaccession and Disposal Information > Deaccession approval` group, where I've left the `Group` field blank in the first entry) 
.. The values don't have to make sense.
.. You can re-use the same authority term in multiple fields, but if fields can be populated by more than one authority vocabulary (like `Current owner` and `Depositor` can both be populated by a Person or Organization authority) make sure you are using all allowed authorities at least once in the record. Here, I used an organization term for `Current owner` and a person term for `Depositor`.
. Save the record
. Get the XML for the record using the API. Details https://github.com/collectionspace/collectionspace-mapper/blob/master/doc/using_cs_api.adoc[here]. My API URL would be: `https://bonsai.dev.collectionspace.org/cspace-services/objectexit/5f12d2f9-de20-4c77-9a93`
.. Save as XML only (browser wording may vary, but you want the raw XML file)
.. Save to `collectionspace-mapper/spec/fixtures/files/xml/{profile}/{recordtypename}{number}.xml`
... For me, since this is the first bonsai objectexit, I'd save `bonsai/objectexit1.xml`


=== 3. Create the datahash for your record

This is a JSON representation of one "row" of imported data.

. Download the appropriate CSV template for your profile/record type from https://github.com/collectionspace/cspace-config-untangler/tree/master/data/templates/release_6_1[here]
. The headers from this CSV will be the names in your JSON name/value pairs. These are usually the underlying XML field names, or a version of them.
. Sometimes it is obvious which CSV column goes with which field in the UI, but sometimes it isn't. Match up with the XML output or use https://github.com/collectionspace/cspace-config-untangler/blob/master/data/fields_6_1_dates_collapsed.csv[fields_6_1_dates_collapsed.csv] to locate which field goes with which UI label.
. Save JSON file in `collectionspace-mapper/spec/fixtures/files/datahashes/{profile}/{recordtypename}{number}.json`
.. The number in the filename should, in most cases, match up with the number in your saved XML file

*Some notes on datahash conventions:*

Example: https://github.com/collectionspace/collectionspace-mapper/blob/master/spec/fixtures/files/datahashes/bonsai/objectexit1.json[`bonsai/objectexit1.json`]

* `exitDateGroup` field is so named because all the very specific structured date fields will be provided by the mapper and nested under the `exitDateGroup` element in the XML hierarchy.
* `exitQuantity` - everything's sent through as a string
* Because I populated the `currentOwner` field with an Organization authority value (Bonsai Museum), I put that value in the `CurrentOwnerOrganization` field of my JSON datahash.
* You do not need to include fields with null values in your JSON datahash. I have them because I like to copy all the headers of the CSV, paste special/transpose them, paste them into Emacs, and use a macro to convert each header to a JSON key with a null value. 
* `exitMethod`
** This is one of the "option list" populated fields mentioned above. The values you see in the record are the display messages. You must record the appropriate term from the `VALUE SOURCE` row of the CSV template in the datahash. This is why I have recorded `inperson` rather than `in person`
** Repeated field delimiter is `;`

Example: https://github.com/collectionspace/collectionspace-mapper/blob/master/spec/fixtures/files/datahashes/anthro/collectionobject2.json[`anthro/collectionobject2.json`]

* Repeating field groups with repeating subgroups
** dimension fields
** title fields
** commingled remains/mortuary treatment fields
** delimiter for repeating values in a subgroup: `^^`
* `title` field -- example for including double quotes if necessary

=== 4. Populate cache with authority and vocabulary term data from your record

Do this in the `spec/{profile}_helpers.rb` file.

Add all field values from your XML file that are output as https://collectionspace.atlassian.net/wiki/spaces/DOC/pages/701467319/RefName[RefNames].

=== 5. Create the test

(to document)

=== 6. Run the test

(to more fully document)

Troubleshoot failing tests caused by data input/output mismatches.

Flag actual mapping problems for Kristina to review.

Change any failing tests to xit.

Commit and make PR, assigning to Kristina for review.

