ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:
:toc-placement!:

= Testing instructions for DDD


toc::[]

== Background
https://www.collectionspace.org/[CollectionSpace] is a collections management application for museums.

We are currently in the middle of an upgrade from CollectionSpace 6.0 to 6.1. *Our work here will focus on version 6.1.*

=== Profiles

Since there are very different types of museum collections (art museum vs. local history museum vs. botanical garden), CollectionSpace offers several different data profiles, all based on the core CollectionSpace profile.

|====================
| Profile | Demo site | Dev site

| Core | https://core.collectionspace.org | https://core.dev.collectionspace.org
| Anthropology  | https://anthro.collectionspace.org | https://anthro.dev.collectionspace.org
| Bonsai  | https://bonsai.collectionspace.org | https://bonsai.dev.collectionspace.org
| Botanical garden  | https://botgarden.collectionspace.org | https://botgarden.dev.collectionspace.org
| Fine & contemporary art  | https://fcart.collectionspace.org | https://fcart.dev.collectionspace.org
| Herbarium  | https://herbarium.collectionspace.org | https://herbarium.dev.collectionspace.org
| Local history & material culture  | https://lhmc.collectionspace.org | https://lhmc.dev.collectionspace.org
| Materials  | https://materials.collectionspace.org | https://materials.dev.collectionspace.org
| Public art  | https://publicart.collectionspace.org | https://publicart.dev.collectionspace.org
|====================

[NOTE]
====
The user name and password for the demo and dev sites are given on the login page. The username follows a consistent pattern across the profiles, and the password for all is the same. The login for demo and dev sites for each profile is the same.
====


[IMPORTANT]
====
The bottom right corner of the login screen tells you the release of CollectionSpace used.

As of 2020-08-31, the demo sites are running 6.0 and the dev sites are running 6.1. *Since we are focusing on 6.1, start off using the dev sites.*

_*If the upgrade is completed during the time you are working on this project, you may see the dev sites jump to 6.2, in which case, you should start using the demo sites which will then be running 6.1.*_
====

=== Record types

There are three main types of record in CollectionSpace: collectionobject, procedure, and authority. To view any record type, open CollectionSpace, click `Create New`, and choose the record type.

collectionobject:: Also called "object" or "cataloging," this record describes an object in a museum's collection. This is the most complex record, with the most fields.
procedure:: A record of this type describes some action taken on an object or group of objects, such as acquisition, conservation activities, exhibition, or movement from one location to another. A procedure record is almost always linked to one or more object records. Procedure records may also be linked to each other. For example, if an object is moved for an exhibition, the movement record and exhibition record may be linked. 
authority:: A record of this type describes a term in a controlled vocabulary (concept, person, geographic place, storage location, etc.). Terms represented by an authority record may be used as values in fields in other records. Some fields require use of an authority term.

There are also vocabulary records, which we tend to deal with only indirectly. A vocabulary is sort of a lightweight version of an authority. It is a controlled term list, but not as much information can be recorded about a term. Some fields require use of a vocabulary term. To view vocabularies and terms in them, log into CollectionSpace, click `Tools`, and click `Term Lists` if you are not already on that tab.

Users with certain permission levels can add new authority and vocabulary terms in the CollectionSpace user interface.

There is another type of controlled term list that must be configured in the CollectionSpace application configuration. This is the "option list." Some fields require option list terms. 

An overview of the different profiles and record types is available on the https://collectionspace.atlassian.net/wiki/spaces/COL/pages/506953729/Configuration+and+Data+Maps+-+Cataloging+Procedures+and+Vocabularies[CollectionSpace wiki]. A comprehensive, sortable, filterable list of all fields in all record types in all profiles is available https://github.com/collectionspace/cspace-config-untangler/blob/master/data/all_fields_6_1_dates_collapsed.csv[here].


== This project

We are building a new batch data import tool that will allow CollectionSpace users to ingest new records or update existing records in bulk, by uploading a CSV file. The working documentation and discussion of the functional design for this tool https://collectionspace.atlassian.net/wiki/spaces/COL/pages/1267236875/CSV+Import+Tool[is available] if you are interested, but *you do not need to look at it*.

This repo represents _one piece_ of this batch data import tool. See https://github.com/collectionspace/collectionspace-mapper/blob/master/README.md[the main repo README file] for a description of what this piece does and how it fits in with the rest.

*The objective of your work on this project is to increase automated test coverage for the code in this repo.* This will include:

- creation of sample CollectionSpace record and saving XML representation of that record via the API
- creation of sample data that would result in that CollectionSpace record
- set up of tests using the sample data and CollectionSpace XML

More details on these steps below!

There are some known issues in the current code, and new tests that fail will help us uncover others, as well as to maintain the functionality of the code as changes are made going forward.


== Getting started

- https://github.com/collectionspace/collectionspace-mapper/blob/master/doc/setup_for_development.adoc[Get set up for development]

== Organizing the work (+ useful reference info)

https://docs.google.com/spreadsheets/d/1nhJRbgGjl7ZCTNlFFI1PnrpoJe-fDML5zMrS275HS3Q/edit?usp=sharing[Google Sheets file for organizing the work]

I gave Erick, Kevin, and Kamore permission to edit the file, so the link should work for you if you log in with a Google account linked to your DDD email.

CollectionSpace isn't always totally consistent, so this spreadsheet also serves as a reference for the internal/code names of different record types, how those record types are _usually_ displayed in the UI, and the pattern for using the CollectionSpace API to retrieve an XML version of a record created in the application.

Priority 1 is highest priority. I will add numbers as the work proceeds.

Put your name in the `claimed_by` column before starting work on a record type, so work doesn't get duplicated.

== Steps

The following steps assume I've chosen the objectexit record type from the bonsai profile.

=== 1. Prepare

. Choose a record type from the spreadsheet to work on and put your name in the `claimed_by` column.
. `cd` into this repo's folder
. `git checkout master` (if not already on master)
. `git pull`
. Create a new branch off master and switch to it: `git checkout -b bonsai-objectexit`
. Log into bonsai CollectionSpace > `Create New` > `Object Exit`

=== 2. Fully populate record in CollectionSpace and save XML

. Fill in the record as fully as possible -- my sample record is at `https://bonsai.dev.collectionspace.org/cspace/bonsai/record/objectexit/5f12d2f9-de20-4c77-9a93`.
.. For repeatable fields or groups of fields, enter more than one value
.. For repeatable field groups, make sure all fields are populated in at least one of the repetitions, but leave a field or two blank, especially in the first grouping, to ensure the mapper can handle these properly. (see the `Deaccession and Disposal Information > Deaccession approval` group, where I've left the `Group` field blank in the first entry) 
.. The values don't have to make sense.
.. You can re-use the same authority term in multiple fields, but if fields can be populated by more than one authority vocabulary (like `Current owner` and `Depositor` can both be populated by a Person or Organization authority) make sure you are using all allowed authorities at least once in the record. Here, I used an organization term for `Current owner` and a person term for `Depositor`.
. Save the record
. Get the XML for the record using the API. Details https://github.com/collectionspace/collectionspace-mapper/blob/master/doc/using_cs_api.adoc[here]. My API URL would be: `https://bonsai.dev.collectionspace.org/cspace-services/objectexit/5f12d2f9-de20-4c77-9a93`
.. Save as XML only (browser wording may vary, but you want the raw XML file)
.. Save to `collectionspace-mapper/spec/fixtures/files/xml/{profile}/{recordtypename}{number}.xml`
... For me, since this is the first bonsai objectexit, I'd save `bonsai/objectexit1.xml`


=== 3. Create the datahash for your record

This is a JSON representation of one "row" of imported data.

. Download the appropriate CSV template for your profile/record type from https://github.com/collectionspace/cspace-config-untangler/tree/master/data/templates/release_6_1[here]
. The headers from this CSV will be the names in your JSON name/value pairs. These are usually the underlying XML field names, or a version of them.
. Sometimes it is obvious which CSV column goes with which field in the UI, but sometimes it isn't. Match up with the XML output or use https://github.com/collectionspace/cspace-config-untangler/blob/master/data/fields_6_1_dates_collapsed.csv[fields_6_1_dates_collapsed.csv] to locate which field goes with which UI label.
. Save JSON file in `collectionspace-mapper/spec/fixtures/files/datahashes/{profile}/{recordtypename}{number}.json`
.. The number in the filename should, in most cases, match up with the number in your saved XML file

*Some notes on datahash conventions:*

Example: https://github.com/collectionspace/collectionspace-mapper/blob/master/spec/fixtures/files/datahashes/bonsai/objectexit1.json[`bonsai/objectexit1.json`]

* `exitDateGroup` field is so named because all the very specific structured date fields will be provided by the mapper and nested under the `exitDateGroup` element in the XML hierarchy.
* `exitQuantity` - everything's sent through as a string
* Because I populated the `currentOwner` field with an Organization authority value (Bonsai Museum), I put that value in the `CurrentOwnerOrganization` field of my JSON datahash.
* You do not need to include fields with null values in your JSON datahash. I have them because I like to copy all the headers of the CSV, paste special/transpose them, paste them into Emacs, and use a macro to convert each header to a JSON key with a null value. 
* `exitMethod`
** This is one of the "option list" populated fields mentioned above. The values you see in the record are the display messages. You must record the appropriate term from the `VALUE SOURCE` row of the CSV template in the datahash. This is why I have recorded `inperson` rather than `in person`
** Repeated field delimiter is `;`

Example: https://github.com/collectionspace/collectionspace-mapper/blob/master/spec/fixtures/files/datahashes/anthro/collectionobject2.json[`anthro/collectionobject2.json`]

* Repeating field groups with repeating subgroups
** dimension fields
** title fields
** commingled remains/mortuary treatment fields
** delimiter for repeating values in a subgroup: `^^`
* `title` field -- example for including double quotes if necessary

=== 4. Populate cache with authority and vocabulary term data from your record

Do this in the `spec/{profile}_helpers.rb` file.

Add all field values from your XML file that are output as https://collectionspace.atlassian.net/wiki/spaces/DOC/pages/701467319/RefName[RefNames].

Follow the patterns currently found in https://github.com/collectionspace/collectionspace-mapper/blob/master/spec/anthro_helpers.rb[anthro_helpers.rb, `populate_anthro`] and https://github.com/collectionspace/collectionspace-mapper/blob/master/spec/bonsai_helpers.rb[bonsai_helpers.rb, `populate_bonsai`].

Best practice: sort the lines in the `terms` array in alphabetical order to make it easy to check for terms in the list and avoid duplication.

Populating the cache manually will cut down on (hopefully eliminate) live API calls made while running tests, and reduce test dependency on another piece of software.

Reuse already set-up terms across records as possible to reduce the amount of work populating the cache.


=== 5. Create the test

==== Organization of tests

General function of the `DataMapper` class is tested in `spec/collectionspace/mapper/data_mapper_spec.rb`.

Record type mapping functionality for each profile is tested in a separate file with naming convention: `spec/collectionspace/mapper/data_mapper_{profile}_spec.rb`. Currently test files exist for anthro and bonsai profiles.

If you need to write a test for a record type in another profile, say core, then you could save a copy of the anthro file as `data_mapper_core_spec.rb` and replace all instances of `anthro` with `core`.

===== Helper files

There is one helper file per profile in the `spec` directory. These have the name pattern `{profile}_helpers.rb`. When a new helper file is created, it needs to be required at the top of `spec/helpers.rb` following the pattern already established there.

==== Internal organization of profile test files

Start off by looking at `spec/collectionspace/mapper/data_mapper_bonsai_spec.rb`.

First we set up a `@config` variable that will be used in all the tests in this file.

Next we set up a context block for `bonsai profile` that contains the rest of the tests. Here we set up the bonsai `@cache` which will be shared by all tests nested within this context block.

Next we set up a context block for `objectexit record`. There should be a context block at this level for each record type. In this block, we set up the `RecordMapper` JSON config (`@rm_bonsai_oe`) for bonsai Object Exit record type. We also set up a `DataHandler` object (`@handler`) using the RecordMapper, cache, client, and config that are already set up. (The `bonsai_client` is set up in the `bonsai_helpers.rb` file.

Next, we set up a context block for object exit record 1. In the `before` block here, we set up all the datahash-specific processing.

- `@datahash` pulls in our JSON data
- `@prepper` creates a `DataPrepper` object that splits repeating values, transforms authority/vocabulary term strings into RefNames, and combines datahash fields that get mapped to the same CollectionSpace XML field
- `@mapper` uses the results of `@prepper` to map the CollectionSpace XML document
- `@mapped_doc` gets this result and uses a helper method to remove the namespaces so we can more easily programmatically compare the documents
- `@mapped_xpaths` uses a helper method to prepare an array of all xpaths in our result
- `@fixture_doc` pulls in the XML we got from the API so the test can compare it to the result. The `get_xml_fixture` method also removes the namespaces and any fields created by the CollectionSpace application that we don't need to worry about in our data payloads.
- `@fixture_xpaths` produces an array of all xpaths to non-blank XML nodes in the fixture record, and removes any associated with fields not covered by the RecordMapper instructions.


Within the `record 1` context block, we finally get to the two tests that are run on this record. These lines follow the pattern `it 'does stuff' do`

The `does not map unexpected fields` test checks that the mapper is not producing extra fields, by comparing the arrays of xpaths.

The `maps as expected` test checks to make sure every field from the fixture document is present and populated as expected in our mapped document.

==== Creating a test for a new record type in bonsai

If I wanted to set up a test for bonsai collectionobject recordtype, I would copy the entire `objectexit record` context block and paste it in the same document. I'd change all the references to `objectexit` or `oe` to `collectionobject` or `co`.

==== Creating tests for a new profile

This is pretty straightforward given that they all follow a similar pattern.

- Create new `spec/collectionspace/mapper/data_mapper_{profile}_spec.rb` file based on another profile
- Create new `spec/{profile}_helpers.rb` file based on the same other profile.
- Find/replace mentions of old profile with the new profile in the new files.
- Create a folder for your new profile in `spec/fixtures/files/datahashes` and `spec/fixtures/files/xml`

=== 6. Run the test and troubleshoot what you can

The following all assumes you are using terminal/command line and are at the base level of the `collectionspace-mapper` repo.

*To run all tests for the application*, do `rake spec`.

This takes a while, so I typically only do it before submitting a pull request, to make sure I haven't inadvertently broken something.

You can see how the `describe`, `context`, and `it` blocks we used to organize the tests create structured test output that describes (when we've done it well) what we expect the code to do.

*To run just the bonsai profile test file*, do `rspec spec/collectionspace/mapper/data_mapper_bonsai_spec.rb`.

This is a lot quicker.

Even quicker, *run only the bonsai objectexit tests* by doing `rspec spec/collectionspace/mapper/data_mapper_bonsai_spec.rb:19`. (The 19 refers to the line on which I currently see `context 'objectexit record' do`.

You can use the same command format, with line number on the end, to run just the tests for a particular objectexit record (`context 'record 1' do` vs. `context 'record 2' do`, if we ever have more than one test for a given record type.

You can also run just one of the `it...do` tests this way, which is the quickest.

Finally, once we have objectexit tests for a number of profiles, you might want to run just those. You can do that: `rspec spec/. --example 'objectexit record'`. See https://relishapp.com/rspec/rspec-core/docs/command-line[rspec command-line documentation] for more info.

==== Basic troubleshooting for test failures

There are two main approaches. Probably the best for getting started is using `puts` or `pp` (pretty print) commands in/around the test that is failing. This approach is usually sufficient for finding failures caused by data input errors or typos.

A more ambitious approach, but one that is very helpful to know about is using `pry`. See fuller article on this https://www.honeybadger.io/blog/debugging-ruby-with-pry/[here], especially if you expect to ever do much in Ruby. The basic idea is to find the place in the actual code (`lib/collectionspace/mapper` files) that is being tested. You can put `binding.pry` anywhere in the code and run a test that calls that code. Pry will interrupt the testing, stop at the line wher you entered `binding.pry`, and let you interact with the code at that exact point from the command line.

You probably don't need the pry approach for this, but I wanted to mention it because it definitely can be very helpful.

[IMPORTANT]
====
Please remove any `puts`, `pp`, `binding.pry` or other lines added for debugging before making a pull request, *unless you think it will be helpful for me to see the same output on something you haven't been able to solve*.

If you are leaving this code in for this reason, please note that in comments on your PR.
====

*If you can make the tests pass*, that is great! But don't worry about it too much, especially at the beginning. You'll pick up on some common problems as we work on these together.

*If you cannot make a test pass*, change the `it` at the beginning of that test to `xit`. For example:

`xit 'maps as expected' do`

This allows you to run `rake spec` or any of the rspec commands without failing tests; it will report them as pending tests instead.

===== `does not map unexpected fields` test

If there are a lot of xpaths in a failing `diff` value for this test, the test output may not show you the whole list.

After the line defining the `diff` variable, add:

`puts diff`

When you run the test again, you should see a list of the unexpected xpaths from @mapped_doc, one per line. 

===== `maps as expected` test

This test is kind of annoying, because if there are 8 errors, the process will be:

- test fails at first error
- you resolve the first problem (or make it skip that one) and run the test again
- test fails at the second error
- repeat, repeat, repeat...

Rspec really doesn't want to make it easy to do this kind of test in a way that will tell you all the errors at once.

Also, the output is cryptic when it fails. It will tell you what was expected (from `@fixture_doc`) and what you got (from `@mapped_doc`), but not what field/xpath the failure was in.

After `@fixture_xpaths.each do |xpath|`, you can add:

`puts xpath`

This will generate a list of all the xpaths it processes (or tries to process). If there is a failure, the last xpath in the list was the problem.

If you want to see the mapped XML document, add the following line directly after `it 'maps as expected' do`:

`puts @mapped_doc`

To see all of the info about how the data has been handled between the original data and the XML mapping, you can add the following line directly after `it 'maps as expected' do`:

`pp(@prepper.prep)`

`pp` is nicer for viewing Hashes or Ruby Objects.

Anything in the `pp(@prepper.prep)` output that is a key starting with `@` can be appended as a method call to get that specific piece of data out by itself. For example, if you think the problem is in how the data was split up, you could do:

`pp(@prepper.prep.split_data)`

*Skipping fields/xpaths*

Because one failing field means the rest of the fields will not be tested, you need to be able to skip field failures you can't fix.

Two methods:

_Skip individual xpaths_

This is useful if there are random one-off fields to skip.

[source,ruby]
----
it 'maps as expected' do
  skip = [
  '/document/objectexit_common/depositor/text()',
  '/document/objectexit_common/deaccessionAuthorizer/text()'
  ]
  @fixture_xpaths.each do |xpath|
     next if skip.any?(xpath)
    fixture_node = standardize_value(@fixture_doc.xpath(xpath).text)
    mapped_node = standardize_value(@mapped_doc.xpath(xpath).text)
    expect(mapped_node).to eq(fixture_node)
  end
end
----

_Skip xpaths matching pattern_

If everything in the `deacApprovalGroupList` is failing, that's eight individual xpaths. Better to do this: 

[source,ruby]
----
it 'maps as expected' do
  @fixture_xpaths.each do |xpath|
     next if xpath.start_with?('/document/objectexit_common/deacApprovalGroupList/')
    fixture_node = standardize_value(@fixture_doc.xpath(xpath).text)
    mapped_node = standardize_value(@mapped_doc.xpath(xpath).text)
    expect(mapped_node).to eq(fixture_node)
  end
end
----

You can also combine these methods:

[source,ruby]
----
it 'maps as expected' do
  skip = [
  '/document/objectexit_common/depositor/text()',
  '/document/objectexit_common/deaccessionAuthorizer/text()'
  ]
  @fixture_xpaths.each do |xpath|
    next if xpath.start_with?('/document/objectexit_common/deacApprovalGroupList/')
    next if skip.any?(xpath)
    fixture_node = standardize_value(@fixture_doc.xpath(xpath).text)
    mapped_node = standardize_value(@mapped_doc.xpath(xpath).text)
    expect(mapped_node).to eq(fixture_node)
  end
end
----



=== 7. Commit your branch and make pull request

Assign the pull request to Kristina for review.

If changes need to be made to your PR, here's how I do that to facilitate best communication/learning. I will:

- make a new branch based on your branch
- make the needed changes in my new version of your branch
- make a pull request from my branch
- make explanatory comments in the code via the PR
- assign my PR to you for review

I think you should then be able to merge my PR into your branch to get the changes. We'll have to experiment with that part.

Sometimes I may make some example changes in my branch to establish a pattern, and I'll ask you to finish those changes in your branch after merging.

Once you've merged and made any remaining changes, request re-review. 


